---
- name: Terraform workflow
  hosts: localhost
  tasks:
    - name: Ensure Terraform directory exists
      file:
        path: terraform/
        state: directory
        mode: '0755'

    - name: Initialize Terraform
      command: terraform init -backend-config="{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
      args:
        chdir: terraform/
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"

    - name: Run Terraform plan
      command: terraform plan -out=tfplan
      args:
        chdir: terraform/
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"

    - name: Encode Terraform plan file into variable
      cloud.terraform.plan_stash:
        path: terraform/tfplan
        var_name: terraform_plan
        state: stash
      no_log: true

    - name: Load Terraform plan from variable
      cloud.terraform.plan_stash:
        path: terraform/tfplan
        var_name: terraform_plan
        state: load
      no_log: true

    - name: Apply Terraform plan
      command: terraform apply tfplan
      args:
        chdir: terraform/
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"
