---
- name: Terraform workflow
  hosts: localhost
  tasks:
    - name: Ensure Terraform directory exists
      file:
        path: terraform/
        state: directory
        mode: '0755'

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: terraform/

    - name: Run Terraform plan
      command: terraform plan -out=tfplan
      args:
        chdir: terraform/

    - name: Encode Terraform plan file into variable
      cloud.terraform.plan_stash:
        path: terraform/tfplan
        var_name: terraform_plan
        state: stash
      no_log: true

    - name: Load Terraform plan from variable
      cloud.terraform.plan_stash:
        path: terraform/tfplan
        var_name: terraform_plan
        state: load
      no_log: true

    - name: Apply Terraform plan
      command: terraform apply tfplan
      args:
        chdir: terraform/
