---
- name: Plan Terraform execution
  hosts: localhost
  tasks:
    - name: Run Terraform plan
      cloud.terraform.terraform:
        project_path: terraform/
        state: planned
        force_init: true
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
        variables:
          gcp_credentials_path: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
          gcp_project: "{{ lookup('env', 'GCE_PROJECT') }}"
        plan_file: /tmp/tfplan
      register: terraform_plan_output

    - name: Stash Terraform plan file
      cloud.terraform.plan_stash:
        path: /tmp/tfplan
        state: stash
      no_log: true
